import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import HeaderComponent from "./layoutUI/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Limelight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderComponent/>
        {children}
        </body>
    </html>
  );
}
